// Code generated by MockGen. DO NOT EDIT.
// Source: broker.go
//
// Generated by this command:
//
//	mockgen -source=broker.go -destination=mock_broker_test.go -package=gocelerypub
//

// Package gocelerypub is a generated GoMock package.
package gocelerypub

import (
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockBroker is a mock of Broker interface.
type MockBroker struct {
	ctrl     *gomock.Controller
	recorder *MockBrokerMockRecorder
	isgomock struct{}
}

// MockBrokerMockRecorder is the mock recorder for MockBroker.
type MockBrokerMockRecorder struct {
	mock *MockBroker
}

// NewMockBroker creates a new mock instance.
func NewMockBroker(ctrl *gomock.Controller) *MockBroker {
	mock := &MockBroker{ctrl: ctrl}
	mock.recorder = &MockBrokerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockBroker) EXPECT() *MockBrokerMockRecorder {
	return m.recorder
}

// CanPublish mocks base method.
func (m *MockBroker) CanPublish() bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CanPublish")
	ret0, _ := ret[0].(bool)
	return ret0
}

// CanPublish indicates an expected call of CanPublish.
func (mr *MockBrokerMockRecorder) CanPublish() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CanPublish", reflect.TypeOf((*MockBroker)(nil).CanPublish))
}

// Reconnect mocks base method.
func (m *MockBroker) Reconnect(host string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reconnect", host)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reconnect indicates an expected call of Reconnect.
func (mr *MockBrokerMockRecorder) Reconnect(host any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reconnect", reflect.TypeOf((*MockBroker)(nil).Reconnect), host)
}

// SendCeleryMessage mocks base method.
func (m *MockBroker) SendCeleryMessage(msg *CeleryMessage) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SendCeleryMessage", msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// SendCeleryMessage indicates an expected call of SendCeleryMessage.
func (mr *MockBrokerMockRecorder) SendCeleryMessage(msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SendCeleryMessage", reflect.TypeOf((*MockBroker)(nil).SendCeleryMessage), msg)
}
